trigger:
- main   # or whatever branch you use

pool:
  vmImage: 'ubuntu-latest'

variables:
  python_version: '3.10'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python_version)'

- checkout: self

# Step 1: Install Python dependencies
- script: |
    python -m pip install --upgrade pip
    pip install JayDeBeApi pandas
  displayName: 'Install Python dependencies'

# Step 2: Download and unzip the JDBC driver
- script: |
    curl -L -o jdbc_driver.zip https://aka.ms/download-jdbc-driver
    unzip jdbc_driver.zip -d jdbc_driver
  displayName: 'Download and unzip JDBC driver'

# Step 3: List contents of unzipped folder to verify correct path (Optional)
- script: |
    ls -R jdbc_driver
  displayName: 'List JDBC driver contents'

# Step 4: Run your Python script (JDBC-based)
- script: |
    python Data-Wrangling.py
  displayName: 'Run your Python script'
