trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  python_version: '3.10'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python_version)'

- checkout: self

# Step 1: Install Python packages including JayDeBeApi
- script: |
    python -m pip install --upgrade pip
    pip install JayDeBeApi pandas
  displayName: 'Install Python dependencies'

# Step 2: Download Microsoft JDBC Driver (single JAR file)
- script: |
    curl -L -o sqljdbc.jar https://aka.ms/download-jdbc-driver
  displayName: 'Download JDBC driver'

# Step 3: Run your Python code (JDBC-based)
- script: |
    python Data-Wrangling.py
  displayName: 'Run your Python script'
