# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main   # or whatever branch you use

pool:
  vmImage: 'ubuntu-latest'

variables:
  python_version: '3.10'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python_version)'

- checkout: self

- script: |
    sudo curl -s https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
    sudo bash -c "curl -s https://packages.microsoft.com/config/ubuntu/$(lsb_release -rs)/prod.list > /etc/apt/sources.list.d/mssql-release.list"
    sudo apt-get update
    sudo apt-get install -y unixodbc-dev msodbcsql18
    python -m pip install --upgrade pip
    pip install pyodbc pandas sqlalchemy
  displayName: 'Install ODBC Driver and dependencies'

- script: |
    python Data-Wrangling.py
  displayName: 'Run your code'