trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  python_version: '3.10'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python_version)'

- checkout: self

# Install Microsoft ODBC Driver for SQL Server
- script: |
    curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
    sudo apt-add-repository https://packages.microsoft.com/ubuntu/20.04/prod
    sudo apt-get update
    sudo ACCEPT_EULA=Y apt-get install -y msodbcsql17 unixodbc-dev
  displayName: 'Install ODBC Driver'

- script: |
    python -m pip install --upgrade pip
    pip install pyodbc pandas sqlalchemy
  displayName: 'Install dependencies'

- script: |
    python Data-Wrangling.py
  displayName: 'Run your code'
